SELECT CAST(Tabular_Place_Data.Poly as INT) as Poly,
CAST(Tabular_Place_Data.NeedA11 AS FLOAT) as NeedA11,
CAST(Tabular_Place_Data.NeedAT11 AS FLOAT) as NeedAT11,
CAST(Tabular_Place_Data.PUnPA11 AS FLOAT) as NeedPA11,
CAST(Tabular_Place_Data.PUnPAT11 AS FLOAT) as NeedPAT11,
CAST(Tabular_Place_Data.PUnPCC11 AS FLOAT) as NeedPCC11,
CAST(Tabular_Place_Data.PUnPCCT11 AS FLOAT) as NeedPCCT11,
CAST(Tabular_Place_Data.NeedA16 AS FLOAT) as NeedA16,
CAST(Tabular_Place_Data.NeedAT16 AS FLOAT) as NeedAT16,
CAST(Tabular_Place_Data.PUnPA16 AS FLOAT) as NeedPA16,
CAST(Tabular_Place_Data.PUnPAT16 AS FLOAT) as NeedPAT16,
CAST(Tabular_Place_Data.PUnPCC16 AS FLOAT) as NeedPCC16,
CAST(Tabular_Place_Data.PUnPCCT16 AS FLOAT) as NeedPCCT16,
CAST(Tabular_Place_Data.places AS FLOAT) as places,
CAST(Tabular_Place_Data.services AS FLOAT) as services ,
CAST(Tabular_Place_Data.bstations AS FLOAT) as bstations ,
CAST(Tabular_Place_Data.roads AS FLOAT) as roads,
CAST(Tabular_Place_Data.Island AS FLOAT) as Island,
CAST(Tabular_Place_Data.Locality AS FLOAT) as Locality,
CAST(Tabular_Place_Data.AGIL AS FLOAT) as AGIL,
CAST(Tabular_Place_Data.MBSP AS FLOAT) as MBSP,
CAST(Tabular_Place_Data.p_N AS FLOAT) as p_N,
CAST(Tabular_Place_Data.p_NE AS FLOAT) as p_NE,
CAST(Tabular_Place_Data.p_E AS FLOAT) as p_E,
CAST(Tabular_Place_Data.p_SE AS FLOAT) as p_SE,
CAST(Tabular_Place_Data.p_S AS FLOAT) as p_S,
CAST(Tabular_Place_Data.p_SW AS FLOAT) as p_SW,
CAST(Tabular_Place_Data.p_W AS FLOAT) as p_W,
CAST(Tabular_Place_Data.p_NW AS FLOAT) as p_NW,
CAST(Tabular_Place_Data.row AS FLOAT) as row,
CAST(Tabular_Place_Data.col AS FLOAT) as col,
CAST(Tabular_Place_Data.est_area AS FLOAT) as est_area,
Shape_Aust.geometry
FROM Shape_Aust 
LEFT JOIN Tabular_Place_Data
ON Shape_Aust.p=CAST(Tabular_Place_Data.Poly as INT)

